language: c
sudo: false

branches:
  only:
    - master

env:
  global:
    - RACKET_DIR=~/racket
  matrix:
#    - RACKET_VERSION=7.0
#    - RACKET_VERSION=7.1
#    - RACKET_VERSION=7.2
    - RACKET_VERSION=7.3
    - RACKET_VERSION=7.4
    - RACKET_VERSION=7.5
    - RACKET_VERSION=HEAD
    - RACKET_VERSION=HEADCS
    - RACKET_VERSION=RELEASE

matrix:
  allow_failures:
    - env: RACKET_VERSION=HEAD
    - env: RACKET_VERSION=HEADCS
    - env: RACKET_VERSION=RELEASE
  fast_finish: true

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ~/travis-racket
  - cat ~/travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"

install:
  - raco pkg install --auto $TRAVIS_BUILD_DIR

before_script:

# Here supply steps such as raco make, raco test, etc.  You can run
# `raco pkg install --deps search-auto` to install any required
# packages without it getting stuck on a confirmation prompt.
script:
  - raco test -c template

after_success:
 - raco setup --check-pkg-deps -p template
 - raco pkg install --deps search-auto cover cover-coveralls
 - raco cover -b -f coveralls -d $TRAVIS_BUILD_DIR/coverage .
